version: '3.8'
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.21.1.0/24"
          gateway: "172.21.1.1"
          ip_range: "172.21.1.128/25"
services:
  traefik:
    image: traefik:v3.3.5 # The official v3 Traefik docker image
    container_name: traefik
#    command: --api.insecure=true --providers.docker # Enables the Web UI and tells Traefik to listen to docker | Disabled as it's being defined in traefik.yaml (config file)
    ports:
      - "80:80" # The HTTP port
      - "81:8080" # The Web UI (enabled by --api.insecure=true | can be disabled afterwards)
      - "443:443"
    env_file:
      - path: ./traefik/.env
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - DOMAIN_URL=${DOMAIN_URL}
      - HOST_URL=${HOST_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik/config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik/config/config.yml:/config.yml:ro
      - ./traefik/data/certs/:/var/traefik/certs/:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.routers.traefik.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.middlewares=default-security-headers@file"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
#      - "traefik.http.routers.traefik-secure.tls.domains[0].main=domain.root" # adjust as required
#      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.domain.root" # adjust as required for wildcard cert
      - "traefik.http.routers.traefik-secure.service=api@internal"
    networks:
      - net
    restart: unless-stopped
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    env_file:
      - path: ./heimdall/.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=europe/dublin
      - DOMAIN_URL=${DOMAIN_URL}
      - HOST_URL=${HOST_URL}
      - SERVICE_NAME=${SERVICE_NAME}
#      - WEB_GUI_CRED=${WEB_GUI_CRED}
    volumes:
      - ./heimdall/data:/config
    ports:
      - 89:80
#      - 6443:443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
#      - "traefik.http.middlewares.${SERVICE_NAME}-auth.basicauth.users=${WEB_GUI_CRED}" # Only enable if auth is needed
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=default-security-headers@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls.certresolver=cloudflare"
#      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=${SERVICE_NAME}-auth" # Only enable if auth is needed
#      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80" # Not required, leaving for doc purposes
    networks:
      - net
    restart: unless-stopped
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - net
  prometheus:
    image: prom/prometheus:latest
    user: "1000"
    env_file:
      - path: ./prometheurs/.env
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN_URL=${DOMAIN_URL}
      - HOST_URL=${HOST_URL}
      - SERVICE_NAME=${SERVICE_NAME}
#      - WEB_GUI_CRED=${WEB_GUI_CRED}
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
#      - "traefik.http.middlewares.${SERVICE_NAME}-auth.basicauth.users=${WEB_GUI_CRED}" # Only enable if auth is needed
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=default-security-headers@file"
#      - "traefik.http.routers.${SERVICE_NAME}-secure.tls.certresolver=cloudflare" # Using "default" cert (config.yml @ traefik) rather than CloudFlare cert (ACME)
#      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=${SERVICE_NAME}-auth" # Only enable if auth is needed
#      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=9090" # Not required, leaving for doc purposes
    networks:
      - net
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - path: ./grafana/.env
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN_URL=${DOMAIN_URL}
      - HOST_URL=${HOST_URL}
      - SERVICE_NAME=${SERVICE_NAME}
#      - WEB_GUI_CRED=${WEB_GUI_CRED}
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
#      - "traefik.http.middlewares.${SERVICE_NAME}-auth.basicauth.users=${WEB_GUI_CRED}" # Only enable if auth is needed
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=default-security-headers@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls.certresolver=cloudflare"
#      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=${SERVICE_NAME}-auth" # Only enable if auth is needed
#      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=3000" # Not required, leaving for doc purposes
    networks:
      - net
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      - net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - net
  telegraf-ping:
    image: telegraf:latest
    container_name: telegraf-ping
    hostname: telegraf-ping
    restart: unless-stopped
    networks:
      - net
    command:
      - '--config=http://influxdb:8086/api/v2/telegrafs/0b18c5e6def1e000'
#    volumes:
#      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - INFLUX_TOKEN=${FLX_TOKEN_TELEGRAF_PING}
    depends_on:
      - influxdb
  telegraf-graphite:
    image: telegraf:latest
    container_name: telegraf-graphite
    hostname: telegraf-graphite
    restart: unless-stopped
    networks:
      - net
    ports:
      - "8094:8094/tcp"
    command:
      - '--config=http://influxdb:8086/api/v2/telegrafs/0e834794deb57000'
#    volumes:
#      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - INFLUX_TOKEN=${FLX_TOKEN_TELEGRAF_GRAPHITE}
    depends_on:
      - influxdb
  telegraf-logs:
    image: telegraf:latest
    container_name: telegraf-syslogs
    hostname: telegraf-syslogs
    restart: unless-stopped
    networks:
      - net
    ports:
      - "6514:6514/udp"
      - "6514:6514/tcp"
    command:
      - '--config=http://influxdb:8086/api/v2/telegrafs/0bc6db3726b57000'
#    volumes:
#      - ./telegraf/telegraf_v2.conf:/etc/telegraf/telegraf.conf
    environment:
      - INFLUX_TOKEN=${FLX_TOKEN_TELEGRAF_SYSLOGS}
    depends_on:
      - rsyslog
      - influxdb
  telegraf-logs2:
    image: telegraf:latest
    container_name: telegraf-syslogs2
    hostname: telegraf-syslogs2
    restart: unless-stopped
    networks:
      - net
    ports:
      - "6515:6515/udp"
      - "6515:6515/tcp"
    command:
      - '--config=http://influxdb:8086/api/v2/telegrafs/0e85879b8fb57000'
#    volumes:
#      - ./telegraf/telegraf_v2.conf:/etc/telegraf/telegraf.conf
    environment:
      - INFLUX_TOKEN=${FLX_TOKEN_TELEGRAF_SYSLOGS2}
    depends_on:
      - rsyslog2
      - influxdb
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    env_file:
      - path: ./influxdb/.env
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN_URL=${DOMAIN_URL}
      - HOST_URL=${HOST_URL}
      - SERVICE_NAME=${SERVICE_NAME}
#      - WEB_GUI_CRED=${WEB_GUI_CRED}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=grafana
      - DOCKER_INFLUXDB_INIT_PASSWORD={FLX_DB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${FLX_DB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=grafana
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
#      - "traefik.http.middlewares.${SERVICE_NAME}-auth.basicauth.users=${WEB_GUI_CRED}" # Only enable if auth is needed
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=default-security-headers@file"
#      - "traefik.http.routers.${SERVICE_NAME}-secure.tls.certresolver=cloudflare" # Using "default" cert (config.yml @ traefik) rather than CloudFlare cert (ACME)
#      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=${SERVICE_NAME}-auth" # Only enable if auth is needed
#      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=9090" # Not required, leaving for doc purposes
    ports:
      - 8086:8086
    networks:
      - net
  rsyslog:
    image: rsyslog/syslog_appliance_alpine:latest
    container_name: rsyslog
    restart: unless-stopped
    volumes:
      - ./rsyslog/work:/work
      - ./rsyslog/config:/config
      - ./rsyslog/logs:/logs
      - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf
    ports:
      - "5514:514/udp"
      - "5514:514/tcp"
    networks:
      net:
        ipv4_address: 172.21.1.5
  rsyslog2:
    image: rsyslog/syslog_appliance_alpine:latest
    container_name: rsyslog2
    restart: unless-stopped
    volumes:
      - ./rsyslog2/work:/work
      - ./rsyslog2/config:/config
      - ./rsyslog2/logs:/logs
      - ./rsyslog2/rsyslog.conf:/etc/rsyslog.conf
    ports:
      - "6516:514/udp"
      - "6516:514/tcp"
    networks:
      net:
        ipv4_address: 172.21.1.6
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    env_file:
      - path: ./uptime-kuma/.env
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN_URL=${DOMAIN_URL}
      - HOST_URL=${HOST_URL}
      - SERVICE_NAME=${SERVICE_NAME}
#      - WEB_GUI_CRED=${WEB_GUI_CRED}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
#      - "traefik.http.middlewares.${SERVICE_NAME}-auth.basicauth.users=${WEB_GUI_CRED}" # Only enable if auth is needed
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=default-security-headers@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls.certresolver=cloudflare"
#      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=${SERVICE_NAME}-auth" # Only enable if auth is needed
#      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=9090" # Not required, leaving for doc purposes
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - net
    volumes:
      - ./uptime-kuma/_data:/app/data
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: ChangeDetection
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file:
      - path: ./changedetection/.env
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN_URL=${DOMAIN_URL}
      - HOST_URL=${HOST_URL}
      - SERVICE_NAME=${SERVICE_NAME}
#      - WEB_GUI_CRED=${WEB_GUI_CRED}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
#      - "traefik.http.middlewares.${SERVICE_NAME}-auth.basicauth.users=${WEB_GUI_CRED}" # Only enable if auth is needed
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${HOST_URL}.${DOMAIN_URL}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=default-security-headers@file"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls.certresolver=cloudflare"
#      - "traefik.http.routers.${SERVICE_NAME}-secure.middlewares=${SERVICE_NAME}-auth" # Only enable if auth is needed
#      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=9090" # Not required, leaving for doc purposes
    networks:
      - net
    volumes:
      - ./changedetection/data:/datastore
